### ISSUE TITLE
faiss_decouple 分支运行 build_precomputedindex 时候 core 掉

### ISSUE THREAD

**Issue by flydt** [orcadt/ivf-hnsw#31]
Loading info from /mnt/hdd_strip/orcv_search/models/hnsw_M16_ef210.bin
Loading data from /mnt/hdd_strip/orcv_search/data/centroids_sift1b.fvecs
Loading edges from /mnt/hdd_strip/orcv_search/models/hnsw_M16_ef210.ivecs
free(): invalid pointer

Thread 1 "build_precomput" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff5854859 in __GI_abort () at abort.c:79
#2  0x00007ffff58bf3ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff59e9285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff58c747c in malloc_printerr (str=str@entry=0x7ffff59e74ae "free(): invalid pointer") at malloc.c:5347
#4  0x00007ffff58c8cac in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
#5  0x00007ffff53a2ca5 in RAND_DRBG_free () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#6  0x00007ffff53790e5 in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#7  0x00007ffff53793af in OPENSSL_cleanup () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#8  0x00007ffff5878a27 in __run_exit_handlers (status=0, listp=0x7ffff5a1a718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true,
    run_dtors=run_dtors@entry=true) at exit.c:108
#9  0x00007ffff5878be0 in __GI_exit (status=<optimized out>) at exit.c:139
#10 0x00007ffff58560ba in __libc_start_main (main=0x5555555691aa <main(int, char**)>, argc=1, argv=0x7fffffffe5f8, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe5e8) at ../csu/libc-start.c:342
#11 0x00005555555690ce in _start ()
(gdb)

**Comment by flydt** [comment]
新的 build 相对稳定，暂时认为已经修复
在 faiss 库的 PQ 类定义中，构造函数出现了 IO 异常
然后触发了析构函数
析构函数释放指针出错
而事实上，IO 完成后才分配的指针
修复方法是 PQ 类对指针变量用  nullptr 初始化
析构函数只能允许释放非 nullptr  的指针
